//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectsCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.ProjectsCommonResource", typeof(ProjectsCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach of project documents.
        /// </summary>
        public static string ACAttachProjectFile {
            get {
                return ResourceManager.GetString("ACAttachProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        public static string ACNewDocument {
            get {
                return ResourceManager.GetString("ACNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string ActionText_Add {
            get {
                return ResourceManager.GetString("ActionText_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload in project documents.
        /// </summary>
        public static string ACUploadFile {
            get {
                return ResourceManager.GetString("ACUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add participants.
        /// </summary>
        public static string AddParticipants {
            get {
                return ResourceManager.GetString("AddParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time.
        /// </summary>
        public static string AddTime {
            get {
                return ResourceManager.GetString("AddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {!groups}.
        /// </summary>
        public static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Followed Projects.
        /// </summary>
        public static string AllFollowedProjects {
            get {
                return ResourceManager.GetString("AllFollowedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Followed Tasks.
        /// </summary>
        public static string AllFollowedTasks {
            get {
                return ResourceManager.GetString("AllFollowedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Projects.
        /// </summary>
        public static string AllMyProjects {
            get {
                return ResourceManager.GetString("AllMyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Tasks.
        /// </summary>
        public static string AllMyTasks {
            get {
                return ResourceManager.GetString("AllMyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All project team.
        /// </summary>
        public static string AllPeopleInProject {
            get {
                return ResourceManager.GetString("AllPeopleInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {!users}.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop Timer.
        /// </summary>
        public static string AutoTimer {
            get {
                return ResourceManager.GetString("AutoTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change view type.
        /// </summary>
        public static string AutoTimerChangeViewType {
            get {
                return ResourceManager.GetString("AutoTimerChangeViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hr:min:sec).
        /// </summary>
        public static string AutoTimerFirstViewType {
            get {
                return ResourceManager.GetString("AutoTimerFirstViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно введено начальное время.
        /// </summary>
        public static string AutoTimerInvalidHoursError {
            get {
                return ResourceManager.GetString("AutoTimerInvalidHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time.
        /// </summary>
        public static string AutoTimerLogHours {
            get {
                return ResourceManager.GetString("AutoTimerLogHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add zero time.
        /// </summary>
        public static string AutoTimerNullTimeError {
            get {
                return ResourceManager.GetString("AutoTimerNullTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string AutoTimerPause {
            get {
                return ResourceManager.GetString("AutoTimerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string AutoTimerReset {
            get {
                return ResourceManager.GetString("AutoTimerReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hours).
        /// </summary>
        public static string AutoTimerSecondViewType {
            get {
                return ResourceManager.GetString("AutoTimerSecondViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string AutoTimerStart {
            get {
                return ResourceManager.GetString("AutoTimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been saved.
        /// </summary>
        public static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to upload.
        /// </summary>
        public static string ChooseaFileToUpload {
            get {
                return ResourceManager.GetString("ChooseaFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, notify all subscribers about changes by e-mail.
        /// </summary>
        public static string ConfirmEmailNotify {
            get {
                return ResourceManager.GetString("ConfirmEmailNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Project.
        /// </summary>
        public static string CreateProjectButtonText {
            get {
                return ResourceManager.GetString("CreateProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize widgets.
        /// </summary>
        public static string CustomizeDashboardLink {
            get {
                return ResourceManager.GetString("CustomizeDashboardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Widgets.
        /// </summary>
        public static string CustomizeWidgets {
            get {
                return ResourceManager.GetString("CustomizeWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your project using:.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start project-related discussion.
        /// </summary>
        public static string DiscussionModuleFirstLine {
            get {
                return ResourceManager.GetString("DiscussionModuleFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite users out of the project.
        /// </summary>
        public static string DiscussionModuleSecondLine {
            get {
                return ResourceManager.GetString("DiscussionModuleSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get feedback from the users&apos; comments.
        /// </summary>
        public static string DiscussionModuleThirdLine {
            get {
                return ResourceManager.GetString("DiscussionModuleThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions.
        /// </summary>
        public static string DiscussionModuleTitle {
            get {
                return ResourceManager.GetString("DiscussionModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of discussions to display.
        /// </summary>
        public static string DiscussionsWidget_Title {
            get {
                return ResourceManager.GetString("DiscussionsWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create documents, spreadsheets, presentations.
        /// </summary>
        public static string DocsModuleFirstLine {
            get {
                return ResourceManager.GetString("DocsModuleFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit them right on the portal.
        /// </summary>
        public static string DocsModuleSecondLine {
            get {
                return ResourceManager.GetString("DocsModuleSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically make them available for the project team.
        /// </summary>
        public static string DocsModuleThirdLine {
            get {
                return ResourceManager.GetString("DocsModuleThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DocsModuleTitle {
            get {
                return ResourceManager.GetString("DocsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {!Users}.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects matching this filter.
        /// </summary>
        public static string Filter_NoProjects {
            get {
                return ResourceManager.GetString("Filter_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed Projects.
        /// </summary>
        public static string FollowedProjects {
            get {
                return ResourceManager.GetString("FollowedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed Tasks.
        /// </summary>
        public static string FollowedTasks {
            get {
                return ResourceManager.GetString("FollowedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the projects you follow.
        /// </summary>
        public static string FollowingProjectsWidget_Description {
            get {
                return ResourceManager.GetString("FollowingProjectsWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You follow no projects.
        /// </summary>
        public static string FollowingProjectsWidget_EmptyString {
            get {
                return ResourceManager.GetString("FollowingProjectsWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of projects.
        /// </summary>
        public static string FollowingProjectsWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("FollowingProjectsWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects to display (1 to 30).
        /// </summary>
        public static string FollowingProjectsWidget_Title {
            get {
                return ResourceManager.GetString("FollowingProjectsWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box if you are not a manager of the project you are creating but wish to track all the changes within it. The information about all the newly created milestones, tasks and discussions will be included into the daily What&apos;s new notification..
        /// </summary>
        public static string HelpAnswerFollowProject {
            get {
                return ResourceManager.GetString("HelpAnswerFollowProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {1}Private Project{2} is a way to restrict the access to your project so that only your team members could access it.{0} Saving your project as a private also allows you to set access rights for each teammate inside this project..
        /// </summary>
        public static string HelpAnswerPrivateProject {
            get {
                return ResourceManager.GetString("HelpAnswerPrivateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {1}Private Project{2} is a way to restrict the access to your project so that only your team members could access it..
        /// </summary>
        public static string HelpAnswerPrivateProjectTeam {
            get {
                return ResourceManager.GetString("HelpAnswerPrivateProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key milestone is used to create a milestone that you consider to be more important than others.{0} All the key milestones are marked by the red key icon placed near its title..
        /// </summary>
        public static string HelpAnswerProjectMilestone {
            get {
                return ResourceManager.GetString("HelpAnswerProjectMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can switch between three project status:{0}{1}Active.{2} All the created projects you are currently working on are marked as active until you do not decide to pause or complete them.{0}{1}Paused.{2} If you decide to temporarily suspend the work on your project, change its status to Paused. To resume the project just make it active setting the corresponding status.{0}{1}Completed.{2} When the work on the project is done and all the tasks are closed, complete your project changing its status to Completed. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpAnswerProjectStatus {
            get {
                return ResourceManager.GetString("HelpAnswerProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add members to your team right now click the {1}Team{2} link and select the users you wish to add from the list.{0} You can also add/remove teammates later clicking the {1}Manage Team{2} link on your project Overview page or switching to the Team tab within this page..
        /// </summary>
        public static string HelpAnswerProjectTeam {
            get {
                return ResourceManager.GetString("HelpAnswerProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, each project team member can view all content inside the selected project: milestones, tasks, documents and discussions. To restrict the access just select the teammate you wish to set access rights for and click one of the links to the right. In this way you can set the access rights for each member of your project team unless he/she does not have portal administrator privileges. The TeamLab administrator has full access to all content across all projects..
        /// </summary>
        public static string HelpAnswerRestrictAccessTeam {
            get {
                return ResourceManager.GetString("HelpAnswerRestrictAccessTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the current report parameters as template allows you to save time and efforts next time you need to generate a report with the same parameters.{0} To see the whole list of the templates use the {1}My Templates{2} link on the Navigation panel.{0} To generate a report on the basis of the created template, select it in the {1}My Templates{2} list and click the {1}Generate{2} link to the right or use the {1}Create new report{2} link on the Navigation panel and select the needed template from the drop- do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpAnswerSaveTemplate {
            get {
                return ResourceManager.GetString("HelpAnswerSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does Follow this project mean?.
        /// </summary>
        public static string HelpQuestionFollowProject {
            get {
                return ResourceManager.GetString("HelpQuestionFollowProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a private project?.
        /// </summary>
        public static string HelpQuestionPrivateProject {
            get {
                return ResourceManager.GetString("HelpQuestionPrivateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does a key milestone mean?.
        /// </summary>
        public static string HelpQuestionProjectMilestone {
            get {
                return ResourceManager.GetString("HelpQuestionProjectMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What project status exist?.
        /// </summary>
        public static string HelpQuestionProjectStatus {
            get {
                return ResourceManager.GetString("HelpQuestionProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to manage your team?.
        /// </summary>
        public static string HelpQuestionProjectTeam {
            get {
                return ResourceManager.GetString("HelpQuestionProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does &apos;save as template&apos; mean?.
        /// </summary>
        public static string HelpQuestionSaveTemplate {
            get {
                return ResourceManager.GetString("HelpQuestionSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string HoursCount {
            get {
                return ResourceManager.GetString("HoursCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Basecamp.
        /// </summary>
        public static string ImportBasecampButtonText {
            get {
                return ResourceManager.GetString("ImportBasecampButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In project.
        /// </summary>
        public static string InProject {
            get {
                return ResourceManager.GetString("InProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        public static string LearnMoreLink {
            get {
                return ResourceManager.GetString("LearnMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the latest discussions.
        /// </summary>
        public static string MessagesWidget_Description {
            get {
                return ResourceManager.GetString("MessagesWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of messages.
        /// </summary>
        public static string MessagesWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("MessagesWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of discussions to display (1 to 30).
        /// </summary>
        public static string MessagesWidget_Title {
            get {
                return ResourceManager.GetString("MessagesWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No discussions started.
        /// </summary>
        public static string MessageWidget_EmptyString {
            get {
                return ResourceManager.GetString("MessageWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark timestamps of your project.
        /// </summary>
        public static string MilestonesModuleFirstLine {
            get {
                return ResourceManager.GetString("MilestonesModuleFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select key milestone.
        /// </summary>
        public static string MilestonesModuleSecondLine {
            get {
                return ResourceManager.GetString("MilestonesModuleSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track milestones using Calendar.
        /// </summary>
        public static string MilestonesModuleThirdLine {
            get {
                return ResourceManager.GetString("MilestonesModuleThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string MilestonesModuleTitle {
            get {
                return ResourceManager.GetString("MilestonesModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of milestones to display (1 to 30).
        /// </summary>
        public static string MilestonesWidget_CountMilestones_Title {
            get {
                return ResourceManager.GetString("MilestonesWidget_CountMilestones_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of milestones.
        /// </summary>
        public static string MilestonesWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("MilestonesWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of my milestones.
        /// </summary>
        public static string MilestonesWidget_MilestonesCount_ErrorMessage {
            get {
                return ResourceManager.GetString("MilestonesWidget_MilestonesCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of my milestones to display.
        /// </summary>
        public static string MilestonesWidget_MilestonesCount_Title {
            get {
                return ResourceManager.GetString("MilestonesWidget_MilestonesCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows overdue milestones.
        /// </summary>
        public static string MilestonesWidget_Overdue_Description {
            get {
                return ResourceManager.GetString("MilestonesWidget_Overdue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overdue milestones.
        /// </summary>
        public static string MilestonesWidget_ShowLate_Title {
            get {
                return ResourceManager.GetString("MilestonesWidget_ShowLate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows upcoming milestones.
        /// </summary>
        public static string MilestonesWidget_Upcoming_Description {
            get {
                return ResourceManager.GetString("MilestonesWidget_Upcoming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec.
        /// </summary>
        public static string MonthNames_short {
            get {
                return ResourceManager.GetString("MonthNames_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MoveToTrash {
            get {
                return ResourceManager.GetString("MoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any tasks.
        /// </summary>
        public static string MyNewTasksWidget_EmptyString {
            get {
                return ResourceManager.GetString("MyNewTasksWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the projects you take part in.
        /// </summary>
        public static string MyProjectsWidget_Description {
            get {
                return ResourceManager.GetString("MyProjectsWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don´t take part in any projects..
        /// </summary>
        public static string MyProjectsWidget_EmptyString {
            get {
                return ResourceManager.GetString("MyProjectsWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of projects.
        /// </summary>
        public static string MyProjectsWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("MyProjectsWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects to display (1 to 30).
        /// </summary>
        public static string MyProjectsWidget_Title {
            get {
                return ResourceManager.GetString("MyProjectsWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows your active tasks.
        /// </summary>
        public static string MyTasksWidget_Description {
            get {
                return ResourceManager.GetString("MyTasksWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of tasks.
        /// </summary>
        public static string MyTasksWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("MyTasksWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tasks to display (1 to 30).
        /// </summary>
        public static string MyTasksWidget_Title {
            get {
                return ResourceManager.GetString("MyTasksWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comments in discussions.
        /// </summary>
        public static string NewCommentForMessage {
            get {
                return ResourceManager.GetString("NewCommentForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comments in milestones.
        /// </summary>
        public static string NewCommentForMilestone {
            get {
                return ResourceManager.GetString("NewCommentForMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comments in tasks.
        /// </summary>
        public static string NewCommentForTask {
            get {
                return ResourceManager.GetString("NewCommentForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the newly created projects.
        /// </summary>
        public static string NewProjectsWidget_Description {
            get {
                return ResourceManager.GetString("NewProjectsWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects added.
        /// </summary>
        public static string NewProjectsWidget_EmptyString {
            get {
                return ResourceManager.GetString("NewProjectsWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of projects.
        /// </summary>
        public static string NewProjectsWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("NewProjectsWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects to display (1 to 30).
        /// </summary>
        public static string NewProjectsWidget_Title {
            get {
                return ResourceManager.GetString("NewProjectsWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        public static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been found.
        /// </summary>
        public static string NothingHasBeenFound {
            get {
                return ResourceManager.GetString("NothingHasBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string NotifyPeopleViaEmail {
            get {
                return ResourceManager.GetString("NotifyPeopleViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string OpenTasks {
            get {
                return ResourceManager.GetString("OpenTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those subscribed to discussion.
        /// </summary>
        public static string PepleSubscribedToMessage {
            get {
                return ResourceManager.GetString("PepleSubscribedToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Projects and Tasks.
        /// </summary>
        public static string PersonalProjAndTasks {
            get {
                return ResourceManager.GetString("PersonalProjAndTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: this action cannot be undone..
        /// </summary>
        public static string PopupNoteUndone {
            get {
                return ResourceManager.GetString("PopupNoteUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        public static string PrevMonth {
            get {
                return ResourceManager.GetString("PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делать все то же, что и менеджер проекта|Назначать менеджера проекта|Создавать и редактировать, удалять любой проект|Создавать/редактировать шаблоны.
        /// </summary>
        public static string ProductAdminOpportunities {
            get {
                return ResourceManager.GetString("ProductAdminOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build teams and assign tasks. Schedule project milestones, track project activity and generate reports..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build teams and assign tasks. Schedule project milestones, track project activity and generate reports..
        /// </summary>
        public static string ProductDescriptionEx {
            get {
                return ResourceManager.GetString("ProductDescriptionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просматривать проекты и участвовать в дискуссиях|Создавать и редактирвать вехи, задачи, дискуссии, документы|Учитывать время выполнения задач, генерировать отчеты|Формировать команду и устанавливать права доступа.
        /// </summary>
        public static string ProductUserOpportunities {
            get {
                return ResourceManager.GetString("ProductUserOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of the projects I follow.
        /// </summary>
        public static string ProjectsWidget_FollowingProjectsCount_ErrorMessage {
            get {
                return ResourceManager.GetString("ProjectsWidget_FollowingProjectsCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the projects I follow to display .
        /// </summary>
        public static string ProjectsWidget_FollowingProjectsCount_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_FollowingProjectsCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of my projects.
        /// </summary>
        public static string ProjectsWidget_MyProjectsCount_ErrorMessage {
            get {
                return ResourceManager.GetString("ProjectsWidget_MyProjectsCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of my projects to display (1 to 30).
        /// </summary>
        public static string ProjectsWidget_MyProjectsCount_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_MyProjectsCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of my projects to display .
        /// </summary>
        public static string ProjectsWidget_PersonalProjectsCount_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_PersonalProjectsCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the projects I follow.
        /// </summary>
        public static string ProjectsWidget_ShowFollowingProjects_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_ShowFollowingProjects_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the tasks I follow.
        /// </summary>
        public static string ProjectsWidget_ShowFollowingTasks_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_ShowFollowingTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only my tasks.
        /// </summary>
        public static string ProjectsWidget_ShowOnlyMyTasks_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_ShowOnlyMyTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of the tasks of the project.
        /// </summary>
        public static string ProjectsWidget_TasksCount_ErrorMessage {
            get {
                return ResourceManager.GetString("ProjectsWidget_TasksCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the tasks of the project to display .
        /// </summary>
        public static string ProjectsWidget_TasksCount_Title {
            get {
                return ResourceManager.GetString("ProjectsWidget_TasksCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string RecentActivityContainerTitle {
            get {
                return ResourceManager.GetString("RecentActivityContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the latest activity across all projects.
        /// </summary>
        public static string RecentActivityWidget_Description {
            get {
                return ResourceManager.GetString("RecentActivityWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent activity.
        /// </summary>
        public static string RecentActivityWidget_EmptyString {
            get {
                return ResourceManager.GetString("RecentActivityWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of actions.
        /// </summary>
        public static string RecentActivityWidget_ErrorMessage {
            get {
                return ResourceManager.GetString("RecentActivityWidget_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of actions to display (1 to 30).
        /// </summary>
        public static string RecentActivityWidget_Title {
            get {
                return ResourceManager.GetString("RecentActivityWidget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate general and detailed reports.
        /// </summary>
        public static string ReportsModuleFirstLine {
            get {
                return ResourceManager.GetString("ReportsModuleFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export them to CSV file or print.
        /// </summary>
        public static string ReportsModuleSecondLine {
            get {
                return ResourceManager.GetString("ReportsModuleSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive automatic reports by email.
        /// </summary>
        public static string ReportsModuleThirdLine {
            get {
                return ResourceManager.GetString("ReportsModuleThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsModuleTitle {
            get {
                return ResourceManager.GetString("ReportsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible(s).
        /// </summary>
        public static string Responsibles {
            get {
                return ResourceManager.GetString("Responsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow 6 easy steps to manage your project effectively.
        /// </summary>
        public static string ScreenBlock_Content {
            get {
                return ResourceManager.GetString("ScreenBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add description, assign project manager.
        /// </summary>
        public static string ScreenBlock1_Content {
            get {
                return ResourceManager.GetString("ScreenBlock1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a project.
        /// </summary>
        public static string ScreenBlock1_Header {
            get {
                return ResourceManager.GetString("ScreenBlock1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work on the project together.
        /// </summary>
        public static string ScreenBlock2_Content {
            get {
                return ResourceManager.GetString("ScreenBlock2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Team.
        /// </summary>
        public static string ScreenBlock2_Header {
            get {
                return ResourceManager.GetString("ScreenBlock2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track progress of your project.
        /// </summary>
        public static string ScreenBlock3_Content {
            get {
                return ResourceManager.GetString("ScreenBlock3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Milestones.
        /// </summary>
        public static string ScreenBlock3_Header {
            get {
                return ResourceManager.GetString("ScreenBlock3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide tasks between team members.
        /// </summary>
        public static string ScreenBlock4_Content {
            get {
                return ResourceManager.GetString("ScreenBlock4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Tasks.
        /// </summary>
        public static string ScreenBlock4_Header {
            get {
                return ResourceManager.GetString("ScreenBlock4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange information with your team.
        /// </summary>
        public static string ScreenBlock5_Content {
            get {
                return ResourceManager.GetString("ScreenBlock5_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Discussion, Upload Files.
        /// </summary>
        public static string ScreenBlock5_Header {
            get {
                return ResourceManager.GetString("ScreenBlock5_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report on project status and workflow.
        /// </summary>
        public static string ScreenBlock6_Content {
            get {
                return ResourceManager.GetString("ScreenBlock6_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Reports.
        /// </summary>
        public static string ScreenBlock6_Header {
            get {
                return ResourceManager.GetString("ScreenBlock6_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Results.
        /// </summary>
        public static string ShowAllResults {
            get {
                return ResourceManager.GetString("ShowAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next.
        /// </summary>
        public static string ShowNext {
            get {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only for my projects and the projects I follow.
        /// </summary>
        public static string ShowOnlyForMyProjects {
            get {
                return ResourceManager.GetString("ShowOnlyForMyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Spent.
        /// </summary>
        public static string SpentTotally {
            get {
                return ResourceManager.GetString("SpentTotally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Products/Projects/.
        /// </summary>
        public static string StartURL {
            get {
                return ResourceManager.GetString("StartURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to comments.
        /// </summary>
        public static string SubscribeOnNewComment {
            get {
                return ResourceManager.GetString("SubscribeOnNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tasks and set the responsible.
        /// </summary>
        public static string TasksModuleFirstLine {
            get {
                return ResourceManager.GetString("TasksModuleFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record time spent on tasks.
        /// </summary>
        public static string TasksModuleSecondLine {
            get {
                return ResourceManager.GetString("TasksModuleSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of tasks using Calendar.
        /// </summary>
        public static string TasksModuleThirdLine {
            get {
                return ResourceManager.GetString("TasksModuleThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksModuleTitle {
            get {
                return ResourceManager.GetString("TasksModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Title.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracking.
        /// </summary>
        public static string TimeTracking {
            get {
                return ResourceManager.GetString("TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Found.
        /// </summary>
        public static string TotalFound {
            get {
                return ResourceManager.GetString("TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total on page.
        /// </summary>
        public static string TotalOnPage {
            get {
                return ResourceManager.GetString("TotalOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Trash.
        /// </summary>
        public static string ToTrash {
            get {
                return ResourceManager.GetString("ToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from comments.
        /// </summary>
        public static string UnSubscribeOnNewComment {
            get {
                return ResourceManager.GetString("UnSubscribeOnNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestones added.
        /// </summary>
        public static string UpcomingMilestonesWidget_EmptyString {
            get {
                return ResourceManager.GetString("UpcomingMilestonesWidget_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadTheFile {
            get {
                return ResourceManager.GetString("UploadTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update File Version.
        /// </summary>
        public static string UploadTheNewVersion {
            get {
                return ResourceManager.GetString("UploadTheNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh.
        /// </summary>
        public static string WatermarkHours {
            get {
                return ResourceManager.GetString("WatermarkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string WatermarkMinutes {
            get {
                return ResourceManager.GetString("WatermarkMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        public static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the selected....
        /// </summary>
        public static string WithSelected {
            get {
                return ResourceManager.GetString("WithSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
