//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.ProjectResource", typeof(ProjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveProject {
            get {
                return ResourceManager.GetString("ActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Projects.
        /// </summary>
        public static string ActiveProjects {
            get {
                return ResourceManager.GetString("ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add first comment.
        /// </summary>
        public static string AddFirstComment {
            get {
                return ResourceManager.GetString("AddFirstComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add milestone.
        /// </summary>
        public static string AddMilestone {
            get {
                return ResourceManager.GetString("AddMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add This Project.
        /// </summary>
        public static string AddNewProject {
            get {
                return ResourceManager.GetString("AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this template.
        /// </summary>
        public static string AddThisTemplate {
            get {
                return ResourceManager.GetString("AddThisTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Projects.
        /// </summary>
        public static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Project Templates.
        /// </summary>
        public static string AllProjectTemplates {
            get {
                return ResourceManager.GetString("AllProjectTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Template {0}.
        /// </summary>
        public static string AppliedTemplate {
            get {
                return ResourceManager.GetString("AppliedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Projects.
        /// </summary>
        public static string ArchiveProjects {
            get {
                return ResourceManager.GetString("ArchiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string ChoosenUsers {
            get {
                return ResourceManager.GetString("ChoosenUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ClosedProject {
            get {
                return ResourceManager.GetString("ClosedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, a project member can view all tasks and set tasks to other teammates. If this option is disabled, a project member can access tasks assigned to him only..
        /// </summary>
        public static string ClosedProjectTeamAllTasksInfoPanel {
            get {
                return ResourceManager.GetString("ClosedProjectTeamAllTasksInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, a project member can view and add discussions..
        /// </summary>
        public static string ClosedProjectTeamDiscussionsInfoPanel {
            get {
                return ResourceManager.GetString("ClosedProjectTeamDiscussionsInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on/off documents.
        /// </summary>
        public static string ClosedProjectTeamDocumentButtonTooltip {
            get {
                return ResourceManager.GetString("ClosedProjectTeamDocumentButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, a project member can view and add documents..
        /// </summary>
        public static string ClosedProjectTeamDocumentsInfoPanel {
            get {
                return ResourceManager.GetString("ClosedProjectTeamDocumentsInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager can.
        /// </summary>
        public static string ClosedProjectTeamManagerPermission {
            get {
                return ResourceManager.GetString("ClosedProjectTeamManagerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add or delete users to/from the project team.
        /// </summary>
        public static string ClosedProjectTeamManagerPermissionArticleA {
            get {
                return ResourceManager.GetString("ClosedProjectTeamManagerPermissionArticleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set access rights for members of the project (for {0}private project{1} only).
        /// </summary>
        public static string ClosedProjectTeamManagerPermissionArticleB {
            get {
                return ResourceManager.GetString("ClosedProjectTeamManagerPermissionArticleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage (create, edit, delete) milestones, tasks, discussions, documents and {2}{0}restrict access to them{1}.
        /// </summary>
        public static string ClosedProjectTeamManagerPermissionArticleC {
            get {
                return ResourceManager.GetString("ClosedProjectTeamManagerPermissionArticleC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on/off discussions.
        /// </summary>
        public static string ClosedProjectTeamMessageButtonTooltip {
            get {
                return ResourceManager.GetString("ClosedProjectTeamMessageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on/off milestones.
        /// </summary>
        public static string ClosedProjectTeamMilestoneButtonTooltip {
            get {
                return ResourceManager.GetString("ClosedProjectTeamMilestoneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, a project member can view all milestones in the project. If this option is disabled, a project member can access milestones with tasks assigned to him only..
        /// </summary>
        public static string ClosedProjectTeamMilestonesInfoPanel {
            get {
                return ResourceManager.GetString("ClosedProjectTeamMilestonesInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on/off tasks.
        /// </summary>
        public static string ClosedProjectTeamTaskButtonTooltip {
            get {
                return ResourceManager.GetString("ClosedProjectTeamTaskButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact via Talk.
        /// </summary>
        public static string ClosedProjectTeamWriteInMessenger {
            get {
                return ResourceManager.GetString("ClosedProjectTeamWriteInMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string ClosedProjectTeamWriteMail {
            get {
                return ResourceManager.GetString("ClosedProjectTeamWriteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавляйте комментарии, что бы написать о ходе работы над задачей или добавить какие-то уточнения.
        /// </summary>
        public static string CommentsDescriptionEmptyList {
            get {
                return ResourceManager.GetString("CommentsDescriptionEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of comments is empty.
        /// </summary>
        public static string CommentsEmptyList {
            get {
                return ResourceManager.GetString("CommentsEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the First Project.
        /// </summary>
        public static string CreateFirstProject {
            get {
                return ResourceManager.GetString("CreateFirstProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from Template.
        /// </summary>
        public static string CreateFromTemplate {
            get {
                return ResourceManager.GetString("CreateFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to create project.
        /// </summary>
        public static string CreateNewProjectRequest {
            get {
                return ResourceManager.GetString("CreateNewProjectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project from template.
        /// </summary>
        public static string CreateProjectFromTemplate {
            get {
                return ResourceManager.GetString("CreateProjectFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project template.
        /// </summary>
        public static string CreateProjectTemplate {
            get {
                return ResourceManager.GetString("CreateProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this project?.
        /// </summary>
        public static string DeleteProjectPopup {
            get {
                return ResourceManager.GetString("DeleteProjectPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project template.
        /// </summary>
        public static string DeleteProjectTemplate {
            get {
                return ResourceManager.GetString("DeleteProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities matching your filter can be displayed in this section.
        /// </summary>
        public static string DescrEmptyListActivitiesFilter {
            get {
                return ResourceManager.GetString("DescrEmptyListActivitiesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects matching your filter can be displayed in this section.
        /// </summary>
        public static string DescrEmptyListProjFilter {
            get {
                return ResourceManager.GetString("DescrEmptyListProjFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to edit project.
        /// </summary>
        public static string EditProjectRequest {
            get {
                return ResourceManager.GetString("EditProjectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {!Users} and Access Rights.
        /// </summary>
        public static string EmployeesAndPermissions {
            get {
                return ResourceManager.GetString("EmployeesAndPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the projects and work effectively.
        /// </summary>
        public static string EmptyListProjDescribe {
            get {
                return ResourceManager.GetString("EmptyListProjDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Projects list is empty.
        /// </summary>
        public static string EmptyListProjHeader {
            get {
                return ResourceManager.GetString("EmptyListProjHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active projects.
        /// </summary>
        public static string EmptyScreenAllActiveProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenAllActiveProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects.
        /// </summary>
        public static string EmptyScreenAllProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenAllProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active projects with this tag.
        /// </summary>
        public static string EmptyScreenByLabelActiveProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenByLabelActiveProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects with this tag.
        /// </summary>
        public static string EmptyScreenByLabelProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenByLabelProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first project.
        /// </summary>
        public static string EmptyScreenHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare templates for similar projects: schedule milestones, build teams and assign tasks..
        /// </summary>
        public static string EmptyScreenHeaderDescribe {
            get {
                return ResourceManager.GetString("EmptyScreenHeaderDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Follow No Active Projects.
        /// </summary>
        public static string EmptyScreenKeepTrackActiveProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenKeepTrackActiveProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Follow No Projects.
        /// </summary>
        public static string EmptyScreenKeepTrackProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenKeepTrackProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects help you organize your workflow, make plans and manage all the team work on the portal. You currently do not participate in any projects. Take part in some projects or follow the projects you do not participate in to be in the know of what&apos;s going on.
        /// </summary>
        public static string EmptyScreenMyActiveProjectsDecscriptionContent {
            get {
                return ResourceManager.GetString("EmptyScreenMyActiveProjectsDecscriptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not participate in any active project.
        /// </summary>
        public static string EmptyScreenMyActiveProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenMyActiveProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not participate in any project.
        /// </summary>
        public static string EmptyScreenMyProjectsHeaderContent {
            get {
                return ResourceManager.GetString("EmptyScreenMyProjectsHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first project template.
        /// </summary>
        public static string EmptyScreenProjectTemplates {
            get {
                return ResourceManager.GetString("EmptyScreenProjectTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send messages, add tasks, plan milestones, manage your team..
        /// </summary>
        public static string EmptyScreenProjectTemplatesDescribe {
            get {
                return ResourceManager.GetString("EmptyScreenProjectTemplatesDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a team for this project template.
        /// </summary>
        public static string EmptyScreenProjectTemplateTeam {
            get {
                return ResourceManager.GetString("EmptyScreenProjectTemplateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the participants for this project..
        /// </summary>
        public static string EmptyScreenProjectTemplateTeamDescription {
            get {
                return ResourceManager.GetString("EmptyScreenProjectTemplateTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the needed tags separating them with commas.
        /// </summary>
        public static string EnterTheTags {
            get {
                return ResourceManager.GetString("EnterTheTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a rule, the name of the project, client, department ....
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no acivities matching this filter.
        /// </summary>
        public static string FilterNoActivities {
            get {
                return ResourceManager.GetString("FilterNoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project news will be included into your What&apos;s New notification e-mail, the project will be available on the Projects tab in the Projects I Follow section and in the All Projects drop-down list on the top..
        /// </summary>
        public static string FollowingLinkTitle {
            get {
                return ResourceManager.GetString("FollowingLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this project.
        /// </summary>
        public static string FollowingProjects {
            get {
                return ResourceManager.GetString("FollowingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Projects.
        /// </summary>
        public static string FollowProjects {
            get {
                return ResourceManager.GetString("FollowProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Project.
        /// </summary>
        public static string HiddenProject {
            get {
                return ResourceManager.GetString("HiddenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Closed Projects.
        /// </summary>
        public static string HideClosedProjects {
            get {
                return ResourceManager.GetString("HideClosedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history for all projects is displayed here: project, milestone, task and subtask creation, editing and completion, changes in the project teams, updates for project discussions, etc..
        /// </summary>
        public static string HistoryNotFound_Body {
            get {
                return ResourceManager.GetString("HistoryNotFound_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to be displayed in this section.
        /// </summary>
        public static string HistoryNotFound_Header {
            get {
                return ResourceManager.GetString("HistoryNotFound_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will be sent to the administrator as a New Project request..
        /// </summary>
        public static string InfoMessageText {
            get {
                return ResourceManager.GetString("InfoMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will be sent to the administrator as a Project Change request..
        /// </summary>
        public static string InfoMessageText2 {
            get {
                return ResourceManager.GetString("InfoMessageText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When deleting a project, be aware that it will be deleted completely with no possibility to restore..
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private project is available only to project manager and project members with corresponding rights..
        /// </summary>
        public static string InformationForHidden {
            get {
                return ResourceManager.GetString("InformationForHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project template title.
        /// </summary>
        public static string InvalidProjectTemplateTitle {
            get {
                return ResourceManager.GetString("InvalidProjectTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand it - DELETE this project..
        /// </summary>
        public static string IUnerstand {
            get {
                return ResourceManager.GetString("IUnerstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I understand it - Save this project as private.
        /// </summary>
        public static string IUnerstandForEditHidden {
            get {
                return ResourceManager.GetString("IUnerstandForEditHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I understand it - Add the project as private.
        /// </summary>
        public static string IUnerstandForHidden {
            get {
                return ResourceManager.GetString("IUnerstandForHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity.
        /// </summary>
        public static string LastActivityDate {
            get {
                return ResourceManager.GetString("LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string LeadPerson {
            get {
                return ResourceManager.GetString("LeadPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingProcessing {
            get {
                return ResourceManager.GetString("LoadingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string LoadingWait {
            get {
                return ResourceManager.GetString("LoadingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Team.
        /// </summary>
        public static string ManagmentTeam {
            get {
                return ResourceManager.GetString("ManagmentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Time Input.
        /// </summary>
        public static string ManualTimeInput {
            get {
                return ResourceManager.GetString("ManualTimeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milestone(s).
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of milestones.
        /// </summary>
        public static string MilestonesNumber {
            get {
                return ResourceManager.GetString("MilestonesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string My {
            get {
                return ResourceManager.GetString("My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Projects.
        /// </summary>
        public static string NewProjects {
            get {
                return ResourceManager.GetString("NewProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activity.
        /// </summary>
        public static string NingNoActivity {
            get {
                return ResourceManager.GetString("NingNoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activity.
        /// </summary>
        public static string NoActivity {
            get {
                return ResourceManager.GetString("NoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not close the project with active milestones..
        /// </summary>
        public static string NotClosedPrjWithActiveMilestone {
            get {
                return ResourceManager.GetString("NotClosedPrjWithActiveMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not close the project with active tasks..
        /// </summary>
        public static string NotClosePrjWithActiveTasks {
            get {
                return ResourceManager.GetString("NotClosePrjWithActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify project manager by e-mail.
        /// </summary>
        public static string NotifyProjectLeader {
            get {
                return ResourceManager.GetString("NotifyProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify project manager by e-mail.
        /// </summary>
        public static string NotifyProjectManager {
            get {
                return ResourceManager.GetString("NotifyProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify project team.
        /// </summary>
        public static string NotifyProjectTeam {
            get {
                return ResourceManager.GetString("NotifyProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t take part in any project.
        /// </summary>
        public static string NotInvolvedInAnyProject {
            get {
                return ResourceManager.GetString("NotInvolvedInAnyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue milestones.
        /// </summary>
        public static string OverdueMilestones {
            get {
                return ResourceManager.GetString("OverdueMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue tasks.
        /// </summary>
        public static string OverdueTasks {
            get {
                return ResourceManager.GetString("OverdueTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string PausedProject {
            get {
                return ResourceManager.GetString("PausedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Project.
        /// </summary>
        public static string PauseProject {
            get {
                return ResourceManager.GetString("PauseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Team.
        /// </summary>
        public static string PeopleOnThisProject {
            get {
                return ResourceManager.GetString("PeopleOnThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string ProjectAdded {
            get {
                return ResourceManager.GetString("ProjectAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Project.
        /// </summary>
        public static string ProjectDeleteButton {
            get {
                return ResourceManager.GetString("ProjectDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectLeader {
            get {
                return ResourceManager.GetString("ProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones of the project.
        /// </summary>
        public static string ProjectMilestones {
            get {
                return ResourceManager.GetString("ProjectMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ProjectOverview {
            get {
                return ResourceManager.GetString("ProjectOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects and Tasks.
        /// </summary>
        public static string ProjectsAndTasks {
            get {
                return ResourceManager.GetString("ProjectsAndTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects By Tag.
        /// </summary>
        public static string ProjectsByLabel {
            get {
                return ResourceManager.GetString("ProjectsByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects By Tag «{0}».
        /// </summary>
        public static string ProjectsByLabelCaption {
            get {
                return ResourceManager.GetString("ProjectsByLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects I Follow.
        /// </summary>
        public static string ProjectsKeepTrack {
            get {
                return ResourceManager.GetString("ProjectsKeepTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks of the project.
        /// </summary>
        public static string ProjectTasks {
            get {
                return ResourceManager.GetString("ProjectTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ProjectTeam {
            get {
                return ResourceManager.GetString("ProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template.
        /// </summary>
        public static string ProjectTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project templates.
        /// </summary>
        public static string ProjectTemplates {
            get {
                return ResourceManager.GetString("ProjectTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template contains a set of messages,  milestones, members and tasks to base new projects on.{0}When you create a new project all templates are available from the dropdown menu saving your time and effort..
        /// </summary>
        public static string ProjectTemplateSetUpDescription {
            get {
                return ResourceManager.GetString("ProjectTemplateSetUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the first discussion.
        /// </summary>
        public static string ProjectTemplateSetupDiscussion {
            get {
                return ResourceManager.GetString("ProjectTemplateSetupDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it&apos;s time to customize your Project Template!.
        /// </summary>
        public static string ProjectTemplateSetUpLabel {
            get {
                return ResourceManager.GetString("ProjectTemplateSetUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the first milestone.
        /// </summary>
        public static string ProjectTemplateSetupMilestone {
            get {
                return ResourceManager.GetString("ProjectTemplateSetupMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign the first task.
        /// </summary>
        public static string ProjectTemplateSetupTask {
            get {
                return ResourceManager.GetString("ProjectTemplateSetupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a team.
        /// </summary>
        public static string ProjectTemplateSetupTeam {
            get {
                return ResourceManager.GetString("ProjectTemplateSetupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Redesign Template or Seminar Template, etc.
        /// </summary>
        public static string ProjectTemplateTitleExample {
            get {
                return ResourceManager.GetString("ProjectTemplateTitleExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responsibles.
        /// </summary>
        public static string Responsibles {
            get {
                return ResourceManager.GetString("Responsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the project as private.
        /// </summary>
        public static string SaveProjectPrivate {
            get {
                return ResourceManager.GetString("SaveProjectPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all project&apos;s milestones.
        /// </summary>
        public static string SeeAllProjectsMilestone {
            get {
                return ResourceManager.GetString("SeeAllProjectsMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View history .
        /// </summary>
        public static string SeeHistory {
            get {
                return ResourceManager.GetString("SeeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project template.
        /// </summary>
        public static string SelectProjectTemplate {
            get {
                return ResourceManager.GetString("SelectProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Closed Projects.
        /// </summary>
        public static string ShowClosedProjects {
            get {
                return ResourceManager.GetString("ShowClosedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next activities.
        /// </summary>
        public static string ShowNextActivities {
            get {
                return ResourceManager.GetString("ShowNextActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next projects.
        /// </summary>
        public static string ShowNextProjects {
            get {
                return ResourceManager.GetString("ShowNextProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task(s).
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks in the projects I follow.
        /// </summary>
        public static string TasksInFollowProjects {
            get {
                return ResourceManager.GetString("TasksInFollowProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tasks.
        /// </summary>
        public static string TasksNumber {
            get {
                return ResourceManager.GetString("TasksNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is being created.
        /// </summary>
        public static string TemplateCreationIsInProgress {
            get {
                return ResourceManager.GetString("TemplateCreationIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: templates are not projects themselves.
        /// </summary>
        public static string TemplateModeAttention {
            get {
                return ResourceManager.GetString("TemplateModeAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow this project.
        /// </summary>
        public static string UnFollowingProjects {
            get {
                return ResourceManager.GetString("UnFollowingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project.
        /// </summary>
        public static string UpdateProject {
            get {
                return ResourceManager.GetString("UpdateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View active milestones.
        /// </summary>
        public static string ViewActiveMilestones {
            get {
                return ResourceManager.GetString("ViewActiveMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View active tasks.
        /// </summary>
        public static string ViewActiveTasks {
            get {
                return ResourceManager.GetString("ViewActiveTasks", resourceCulture);
            }
        }
    }
}
