//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeTrackingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeTrackingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.TimeTrackingResource", typeof(TimeTrackingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ClosedTasks {
            get {
                return ResourceManager.GetString("ClosedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timers matching your filter can be displayed in this section..
        /// </summary>
        public static string DescrEmptyListTimersFilter {
            get {
                return ResourceManager.GetString("DescrEmptyListTimersFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timers.
        /// </summary>
        public static string NoTimersFilter {
            get {
                return ResourceManager.GetString("NoTimersFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note down the time that you spend on a task in your project for even more effective time management. Start the timer at the beginning of the task and stop it once the task is completed. Add the calculated time to the selected task..
        /// </summary>
        public static string NoTimersNote {
            get {
                return ResourceManager.GetString("NoTimersNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timers have been started yet.
        /// </summary>
        public static string NoTtimers {
            get {
                return ResourceManager.GetString("NoTtimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenTasks {
            get {
                return ResourceManager.GetString("OpenTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timer.
        /// </summary>
        public static string StartTimer {
            get {
                return ResourceManager.GetString("StartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Spend.
        /// </summary>
        public static string TotalTimeSpend {
            get {
                return ResourceManager.GetString("TotalTimeSpend", resourceCulture);
            }
        }
    }
}
