//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Projects.Core.Services.NotifyService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatternResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatternResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Projects.Core.Services.NotifyService.PatternResource", typeof(PatternResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Discussion Edited: &quot;${EntityTitle}&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has edited the discussion: &quot;${EntityTitle}&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;&quot;: 
        ///
        ///$AdditionalData.get_item(&quot;MessagePreview&quot;) 
        ///
        ///#foreach($fileInfo in $AdditionalData.get_item(&quot;&quot;Files&quot;&quot;).Keys) 
        ///
        ///#beforeall 
        ///
        ///---------------------------------------- 
        ///
        ///#each 
        ///
        ///&quot;$fileInfo&quot;:&quot;$Additio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_EditMessage {
            get {
                return ResourceManager.GetString("pattern_EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Projects. Import of the data from Basecamp
        ///
        ///The new data has been successfully imported
        ///
        ///Your portal address: &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot;
        ///
        ///&quot;Edit subscription settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.
        /// </summary>
        internal static string pattern_ImportData {
            get {
                return ResourceManager.GetString("pattern_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.You have been Added to the Project Team: &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added you to the team of the project:[&quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot;] 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage your &quot;subscription settings&quot;:&quot;$R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_InviteToProject {
            get {
                return ResourceManager.GetString("pattern_InviteToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Overdue Milestone Notification: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#sortBy=deadline&amp;sortOrder=ascending&quot; 
        ///
        ///The &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID&quot; milestone of the project &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; is overdue. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To chan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_LateMilestone {
            get {
                return ResourceManager.GetString("pattern_LateMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Milestone Closed: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#status=closed&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has closed the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#status=closed&quot; milestone in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project.
        ///
        /// ^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_MilestoneClosed {
            get {
                return ResourceManager.GetString("pattern_MilestoneClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Milestone Created: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new milestone: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#sortBy=create_on&amp;sortOrder=descending&quot; to the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_MilestoneCreated {
            get {
                return ResourceManager.GetString("pattern_MilestoneCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Milestone Due Date Notification: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; 
        ///
        ///Less than 48 hours is left till the due date of the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; milestone in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project.
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_MilestoneDeadline {
            get {
                return ResourceManager.GetString("pattern_MilestoneDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Milestone Edited: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has edited the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; milestone in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_MilestoneEdited {
            get {
                return ResourceManager.GetString("pattern_MilestoneEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Comment to Discussion: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new comment to the discussion: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$AdditionalData 
        ///
        ///&quot;Read more&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///^You receive this email because you are a registered user of the &quot;$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_NewCommentForMessage {
            get {
                return ResourceManager.GetString("pattern_NewCommentForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Comment to Milestone: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new comment to the milestone:
        ///
        ///$AdditionalData
        ///
        ///&quot;Read more&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;
        ///
        ///Your portal address: &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot;
        ///
        ///&quot;Edit subscription settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.
        /// </summary>
        internal static string pattern_NewCommentForMilestone {
            get {
                return ResourceManager.GetString("pattern_NewCommentForMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Comment to Task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new comment to the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task: 
        ///
        ///$AdditionalData
        ///
        ///&quot;Read more&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_NewCommentForTask {
            get {
                return ResourceManager.GetString("pattern_NewCommentForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Discussion Created: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has started a new discussion: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/messages.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;: 
        ///
        ///$AdditionalData.get_item(&quot;MessagePreview&quot;) 
        ///
        ///#foreach($fileInfo in $AdditionalData.get_item(&quot;Files&quot;).Keys)
        ///
        ///#beforeall
        ///
        ///---------------------------------------- 
        ///
        ///#each 
        ///
        ///&quot;$fileInfo&quot;:&quot;$Addition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_NewMessage {
            get {
                return ResourceManager.GetString("pattern_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Reminder about the Task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; reminds you about the task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;: $AdditionalData.get_item(&quot;TaskDescription&quot;) 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ReminderAboutTask {
            get {
                return ResourceManager.GetString("pattern_ReminderAboutTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Reminder about the Task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///Today is the deadline for the task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;: $AdditionalData.get_item(&quot;TaskDescription&quot;) 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage your &quot;subscription settings&quot;:&quot;$Reci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ReminderAboutTaskDeadline {
            get {
                return ResourceManager.GetString("pattern_ReminderAboutTaskDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.You have been Removed from the Project Team: &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot;
        ///
        /// $__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has removed you from the team of the project: &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot;
        ///
        /// ^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage your &quot;subscription settin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_RemoveFromProject {
            get {
                return ResourceManager.GetString("pattern_RemoveFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Milestone Assigned to You: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has appointed you responsible for the milestone: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/milestones.aspx?prjID=$ProjectID#my=true&quot; in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ResponsibleForMilestone {
            get {
                return ResourceManager.GetString("pattern_ResponsibleForMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.You were Appointed as Project Manager: &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has appointed you as manager of the project &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot;: 
        ///
        ///$AdditionalData 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage your &quot;subscr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ResponsibleForProject {
            get {
                return ResourceManager.GetString("pattern_ResponsibleForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Subtask Assigned to You: &quot;$SubEntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has appointed you responsible for the subtask: &quot;$SubEntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; added to the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task:
        ///
        ///$AdditionalData.get_item(&quot;TaskDescription&quot;) 
        ///
        ///^You receive this email [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ResponsibleForSubTask {
            get {
                return ResourceManager.GetString("pattern_ResponsibleForSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Assigned to You: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;&quot;$__AuthorUrl&quot;&quot; has appointed you responsible for the task: &quot;&quot;$EntityTitle&quot;&quot;:&quot;&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;&quot; in the &quot;&quot;$ProjectTitle&quot;&quot;:&quot;&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;&quot; project: 
        ///
        ///$AdditionalData.get_item(&quot;&quot;TaskDescription&quot;&quot;) 
        ///
        ///^You receive this ema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_ResponsibleForTask {
            get {
                return ResourceManager.GetString("pattern_ResponsibleForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Subtask Closed: &quot;$SubEntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has closed the subtask added to the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. If you don&apos;t want to receive the notifications about this task, please &quot;unsubscribe&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_SubTaskClosed {
            get {
                return ResourceManager.GetString("pattern_SubTaskClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Subtask Created: &quot;$SubEntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new subtask: &quot;$SubEntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; to the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task. 
        ///
        ///The subtask is assigned to &quot;$Responsible&quot;. 
        ///
        ///^You receive this email because you are a registered user o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_SubTaskCreated {
            get {
                return ResourceManager.GetString("pattern_SubTaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Subtask Deleted: &quot;$SubEntityTitle&quot;
        ///
        /// $__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has deleted the subtask: &quot;$SubEntityTitle&quot; of the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. If you don&apos;t want to receive the notifications about this task, please &quot;unsubscribe&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_SubTaskDeleted {
            get {
                return ResourceManager.GetString("pattern_SubTaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Subtask Resumed: &quot;$SubEntityTitle&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has resumed the subtask: &quot;$SubEntityTitle&quot; of the &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task. 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. If you don&apos;t want to receive the notifications about this task, please &quot;unsubscribe&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_SubTaskResumed {
            get {
                return ResourceManager.GetString("pattern_SubTaskResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Closed: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot;&quot; has closed the task &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project: 
        ///
        ///$AdditionalData 
        ///
        /// ^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_TaskClosed {
            get {
                return ResourceManager.GetString("pattern_TaskClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Created: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has added a new task: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; to the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project:
        ///
        /// $AdditionalData.get_item(&quot;TaskDescription&quot;) 
        ///
        ///The task is assigned to &quot;$Responsible&quot;
        ///
        /// ^You receive this email because y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_TaskCreated {
            get {
                return ResourceManager.GetString("pattern_TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Deleted: &quot;$EntityTitle&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has deleted the task &quot;$EntityTitle&quot; in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project:
        ///
        ///$AdditionalData 
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To change the notification type, please manage your &quot;subscription settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.^.
        /// </summary>
        internal static string pattern_TaskDeleted {
            get {
                return ResourceManager.GetString("pattern_TaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Edited: &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot;  
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has edited the  &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; task in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project.
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. To chan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_TaskEdited {
            get {
                return ResourceManager.GetString("pattern_TaskEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Task Resumed:  &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; 
        ///
        ///$__DateTime &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has resumed the task &quot;$EntityTitle&quot;:&quot;${__VirtualRootPath}/products/projects/tasks.aspx?prjID=$ProjectID&amp;ID=$EntityID&quot; in the &quot;$ProjectTitle&quot;:&quot;${__VirtualRootPath}/products/projects/projects.aspx?prjID=$ProjectID&quot; project: 
        ///
        ///$AdditionalData
        ///
        /// ^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRoot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_TaskResumed {
            get {
                return ResourceManager.GetString("pattern_TaskResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Discussion Edited: $EntityTitle.
        /// </summary>
        internal static string subject_EditMessage {
            get {
                return ResourceManager.GetString("subject_EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects. Import of the data from Basecamp.
        /// </summary>
        internal static string subject_ImportData {
            get {
                return ResourceManager.GetString("subject_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. You have been Added to the Project Team.
        /// </summary>
        internal static string subject_InviteToProject {
            get {
                return ResourceManager.GetString("subject_InviteToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Overdue Milestone Notification: $EntityTitle.
        /// </summary>
        internal static string subject_LateMilestone {
            get {
                return ResourceManager.GetString("subject_LateMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Milestone Closed: $EntityTitle.
        /// </summary>
        internal static string subject_MilestoneClosed {
            get {
                return ResourceManager.GetString("subject_MilestoneClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Milestone Created: $EntityTitle.
        /// </summary>
        internal static string subject_MilestoneCreated {
            get {
                return ResourceManager.GetString("subject_MilestoneCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Milestone Due Date Notification: $EntityTitle.
        /// </summary>
        internal static string subject_MilestoneDeadline {
            get {
                return ResourceManager.GetString("subject_MilestoneDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Milestone Edited: $EntityTitle.
        /// </summary>
        internal static string subject_MilestoneEdited {
            get {
                return ResourceManager.GetString("subject_MilestoneEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. New Comment to Discussion: $EntityTitle.
        /// </summary>
        internal static string subject_NewCommentForMessage {
            get {
                return ResourceManager.GetString("subject_NewCommentForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. New Comment to Milestone: $EntityTitle.
        /// </summary>
        internal static string subject_NewCommentForMilestone {
            get {
                return ResourceManager.GetString("subject_NewCommentForMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. New Comment to Task: $EntityTitle.
        /// </summary>
        internal static string subject_NewCommentForTask {
            get {
                return ResourceManager.GetString("subject_NewCommentForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. New Discussion: $EntityTitle.
        /// </summary>
        internal static string subject_NewMessage {
            get {
                return ResourceManager.GetString("subject_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Remind about the task: $EntityTitle.
        /// </summary>
        internal static string subject_ReminderAboutTask {
            get {
                return ResourceManager.GetString("subject_ReminderAboutTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Remind about the task: $EntityTitle.
        /// </summary>
        internal static string subject_ReminderAboutTaskDeadline {
            get {
                return ResourceManager.GetString("subject_ReminderAboutTaskDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. You have been Removed from the Project Team.
        /// </summary>
        internal static string subject_RemoveFromProject {
            get {
                return ResourceManager.GetString("subject_RemoveFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Milestone Assigned to You: $EntityTitle.
        /// </summary>
        internal static string subject_ResponsibleForMilestone {
            get {
                return ResourceManager.GetString("subject_ResponsibleForMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. You Were Appointed as Project Manager.
        /// </summary>
        internal static string subject_ResponsibleForProject {
            get {
                return ResourceManager.GetString("subject_ResponsibleForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. SubTask Assigned to You: $SubEntityTitle.
        /// </summary>
        internal static string subject_ResponsibleForSubTask {
            get {
                return ResourceManager.GetString("subject_ResponsibleForSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Assigned to You: $EntityTitle.
        /// </summary>
        internal static string subject_ResponsibleForTask {
            get {
                return ResourceManager.GetString("subject_ResponsibleForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Subtask Closed: $SubEntityTitle.
        /// </summary>
        internal static string subject_SubTaskClosed {
            get {
                return ResourceManager.GetString("subject_SubTaskClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Subtask Created: $SubEntityTitle.
        /// </summary>
        internal static string subject_SubTaskCreated {
            get {
                return ResourceManager.GetString("subject_SubTaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. SubTask Deleted: $SubEntityTitle.
        /// </summary>
        internal static string subject_SubTaskDeleted {
            get {
                return ResourceManager.GetString("subject_SubTaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Subtask Resumed: $SubEntityTitle.
        /// </summary>
        internal static string subject_SubTaskResumed {
            get {
                return ResourceManager.GetString("subject_SubTaskResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Closed: $EntityTitle.
        /// </summary>
        internal static string subject_TaskClosed {
            get {
                return ResourceManager.GetString("subject_TaskClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Created: $EntityTitle.
        /// </summary>
        internal static string subject_TaskCreated {
            get {
                return ResourceManager.GetString("subject_TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Deleted: $EntityTitle.
        /// </summary>
        internal static string subject_TaskDeleted {
            get {
                return ResourceManager.GetString("subject_TaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Edited: $EntityTitle.
        /// </summary>
        internal static string subject_TaskEdited {
            get {
                return ResourceManager.GetString("subject_TaskEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects [$ProjectTitle]. Task Resumed: $EntityTitle.
        /// </summary>
        internal static string subject_TaskResumed {
            get {
                return ResourceManager.GetString("subject_TaskResumed", resourceCulture);
            }
        }
    }
}
