//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.Core.Notify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebstudioPatternResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebstudioPatternResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.Core.Notify.WebstudioPatternResource", typeof(WebstudioPatternResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1. You&apos;re Invited to Join $__AuthorName&apos;s &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot; Portal
        ///
        ///Hello $UserDisplayName,
        ///
        ///$__AuthorName has invited you to join his/her portal at TeamLab platform - &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot;.
        ///
        ///To accept the invitation please enter your name and password following this link:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the operation within that period.
        ///
        ///Joining $__AuthorName&apos;s portal you can:
        ///
        ///* participate in blogs an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_activate {
            get {
                return ResourceManager.GetString("pattern_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Activate Your Email for &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot; Portal.
        ///
        ///Hello $UserDisplayName,
        ///
        ///To start participating in the &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot; portal life you need to activate your email address. This is done for security reasons.
        ///
        ///Please follow the link below or access the link by copying and pasting it to your Internet browser&apos;s address bar:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete your email activation within that period.
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_activate_email {
            get {
                return ResourceManager.GetString("pattern_activate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.&quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal Backup Created
        ///
        ///Dear $OwnerName,
        ///
        ///A backup file containing data from your &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal has been created. It is available for download under the following link:
        ///&quot;$BackupUrl&quot;:&quot;$BackupUrl&quot;
        ///
        ///*Note*: this link is valid for $BackupHours hours only. Please complete the operation within that period.
        ///
        ///To learn more on the backup/restore procedure please refer to our &quot;How to Create and Restore the TeamLab Portal B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_backup_created {
            get {
                return ResourceManager.GetString("pattern_backup_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Email Address Change Request
        ///
        ///You have requested to change your email address used to enter the TeamLab portal.
        ///
        ///Please follow the link below to change your email address:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete your email change process within that period.
        ///
        ///If you do not want to change your email or received this email by mistake, please ignore it or contact your portal administrator to find out the details.
        ///
        ///If you have any questions or need a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_change_email {
            get {
                return ResourceManager.GetString("pattern_change_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Password Change Request for the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal
        ///
        ///There has been a request to change your password used to enter the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal.
        ///
        ///Please follow the link below to change your password:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the password change process within that period.
        ///
        ///If you do not want to change your password or received this email by mistake, please ignore it or co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_change_password {
            get {
                return ResourceManager.GetString("pattern_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Mobile Phone Change Request
        ///
        ///You have requested to change your mobile phone used to enter the TeamLab portal.
        ///
        ///Please follow the link below to change your mobile phone:
        ///
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///If you do not want to change your mobile phone or received this email by mistake, please ignore it or contact your portal administrator to find out the details..
        /// </summary>
        internal static string pattern_change_phone {
            get {
                return ResourceManager.GetString("pattern_change_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outdated].
        /// </summary>
        internal static string pattern_change_pwd {
            get {
                return ResourceManager.GetString("pattern_change_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Change of &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal Owner
        ///
        ///Dear $OwnerName,
        ///
        ///There has been a request to change the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal owner to $UserName.
        ///
        ///Please follow the link below to confirm the operation:
        ///&quot;$ConfirmPortalOwnerUpdate&quot;:&quot;$ConfirmPortalOwnerUpdate&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the portal owner change process within that period.  
        ///
        ///
        ///If you have any questions or need assistance please feel free to con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_confirm_owner_change {
            get {
                return ResourceManager.GetString("pattern_confirm_owner_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Welcome to TeamLab!
        ///
        ///Dear $UserName
        ///
        ///Your portal has been created at &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot;
        ///
        ///h2.Get started with your portal
        ///&quot;Watch video&quot;:&quot;http://www.teamlab.com/Help/Video/TL-FreeBusiness.aspx&quot;
        ///
        ///* - &quot;Invite employees&quot;:&quot;${__VirtualRootPath}&quot; to join your portal.
        ///* - Change your company &quot;name and logo&quot;:&quot;${__VirtualRootPath}/management.aspx?type=7&quot;, as well as many other portal settings.
        ///* - Edit your &quot;profile&quot;:&quot;${__VirtualRootPath}/my.aspx&quot; to add personal and contact de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_congratulations {
            get {
                return ResourceManager.GetString("pattern_congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Change of Portal Address
        ///
        ///Dear $OwnerName,
        ///
        ///There has been a request to change the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal address to &quot;$PortalAddress&quot;:&quot;$PortalAddress&quot; #if($PortalDns != &quot;&quot;) (&quot;$PortalDns&quot;:&quot;$PortalDns&quot; )#end.
        ///
        ///Please follow the link below to confirm the operation:
        ///&quot;$ConfirmDnsUpdate&quot;:&quot;$ConfirmDnsUpdate&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the portal address change process within that period.  
        ///
        ///
        ///If you have any questions or need assistance  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_dns_change {
            get {
                return ResourceManager.GetString("pattern_dns_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: $UserEmail 
        ///
        ///$Body.
        /// </summary>
        internal static string pattern_for_admin_notify {
            get {
                return ResourceManager.GetString("pattern_for_admin_notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Invitation to Join TeamLab Portal
        ///
        ///Hello $UserDisplayName,
        ///
        ///$__AuthorName has invited you to join a portal at Teamlab - a corporate platform for document and project management. Join the portal and start collaborating with your colleagues right away.
        ///
        ///To accept the invitation please enter your name and password following this link:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 48 hours only. Please complete the operation within that period.
        ///
        ///If you have any questions or need assi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_invite {
            get {
                return ResourceManager.GetString("pattern_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Invitation to Join &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot; Portal
        ///
        ///Hello,
        ///
        ///You have requested to join the &quot;${__VirtualRootPath}&quot;:&quot;$InviteLink&quot; portal at Teamlab - a platform for document and project management. Join the portal and start collaborating with your colleagues or friends right away.
        ///
        ///To accept the invitation please enter your name and password following this link:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 48 hours only. Please complete the operation within that period.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_join {
            get {
                return ResourceManager.GetString("pattern_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Deactivation of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal
        ///
        ///Dear $OwnerName,
        ///
        ///You have requested a temporary deactivation of your &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. Please follow the link below to confirm the operation:
        ///&quot;$DeactivateUrl&quot;:&quot;$DeactivateUrl&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the portal deactivation process within that period. 
        ///
        ///You can reactivate your portal any time by clicking the following link:
        ///&quot;$ActivateUrl&quot;:&quot;$Activate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_portal_deactivate {
            get {
                return ResourceManager.GetString("pattern_portal_deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Deletion of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal
        ///
        ///Dear $OwnerName,
        ///
        ///You have requested to permanently delete your &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal.
        ///
        ///*Important! All the data stored on your portal, as well as your registration details will be lost and cannot be recovered.*
        ///
        ///If you still want to delete your &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal please follow the link below to confirm the operation:
        ///&quot;$DeleteUrl&quot;:&quot;$DeleteUrl&quot;
        ///
        ///*Note*: this lin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_portal_delete {
            get {
                return ResourceManager.GetString("pattern_portal_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Removal of the Profile from the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal
        ///
        ///You have requested to permanently delete your profile from the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal.
        ///
        ///If you still want to delete your profile please follow the link below to confirm the operation:
        ///&quot;$InviteLink&quot;:&quot;$InviteLink&quot;
        ///
        ///*Note*: this link is valid for 7 days only. Please complete the profile deletion process within that period. 
        ///
        ///
        ///If you have any questions or need assistance please feel f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_profile_delete {
            get {
                return ResourceManager.GetString("pattern_profile_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Your Profile at &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot; has been Changed
        ///
        ///Dear $UserName,
        ///
        ///Your user profile details at &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot; have been changed by &quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot;.
        ///
        ///To view your profile follow the link below:
        ///&quot;$UserName&quot;:&quot;$MyStaffLink&quot;
        ///
        ///
        ///^You receive this email because you are a registered user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal.^.
        /// </summary>
        internal static string pattern_profile_updated {
            get {
                return ResourceManager.GetString("pattern_profile_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outdated].
        /// </summary>
        internal static string pattern_pwd_reminder {
            get {
                return ResourceManager.GetString("pattern_pwd_reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.&quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal Profile Change Notification
        ///
        ///&quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has changed his/her profile details at the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal.
        ///
        ///
        ///^You receive this email because you are an administrator of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. If you do not want to receive the notifications about profile updates, please manage your &quot;subscription settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.^.
        /// </summary>
        internal static string pattern_self_profile_updated {
            get {
                return ResourceManager.GetString("pattern_self_profile_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.What&apos;s New on &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal for $Date
        ///
        ///#foreach($activity in $Activities)
        ///
        ///h2.$activity.Key
        ///
        ///#foreach($whatsNewActivity in $activity.Value)
        ///#foreach($b in $whatsNewActivity.BreadCrumbs) h3.$b
        ///#end &quot;$whatsNewActivity.Title&quot;:&quot;$whatsNewActivity.URL&quot;
        ///*Author*: &quot;$whatsNewActivity.UserName&quot;:&quot;$whatsNewActivity.UserAbsoluteURL&quot;, published: $whatsNewActivity.Date.ToShortTimeString()
        /// 
        /// 
        ///#end
        /// 
        ///#end
        ///
        ///
        ///^You receive this email because you are a registered user  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_send_whats_new {
            get {
                return ResourceManager.GetString("pattern_send_whats_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New User Added to &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal
        ///
        ///&quot;$__AuthorName&quot;:&quot;$__AuthorUrl&quot; has joined your portal at &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot;.
        ///
        ///
        ///^You receive this email because you are an administrator user of the &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; portal. If you do not want to receive the notifications about new users, please manage your &quot;subscription settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.^.
        /// </summary>
        internal static string pattern_user_has_join {
            get {
                return ResourceManager.GetString("pattern_user_has_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outdated].
        /// </summary>
        internal static string pattern_you_added {
            get {
                return ResourceManager.GetString("pattern_you_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Welcome to &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot; Portal!
        ///
        ///Dear $UserName,
        ///
        ///Your user profile has been successfully added to the portal at &quot;${__VirtualRootPath}&quot;:&quot;${__VirtualRootPath}&quot;.
        ///
        ///h3.Get started with your portal
        ///
        ///# Edit your &quot;profile&quot;:&quot;$MyStaffLink&quot; to add personal and contact details.
        ///# Use &quot;Community&quot;:&quot;${__VirtualRootPath}/products/community/&quot; to start your blogs, forums, add events, photos, and more.
        ///# Create &quot;Projects&quot;:&quot;${__VirtualRootPath}/products/projects/&quot; and manage your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern_you_added_after_invite {
            get {
                return ResourceManager.GetString("pattern_you_added_after_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation from $__AuthorName to Join ${__VirtualRootPath} Portal.
        /// </summary>
        internal static string subject_activate {
            get {
                return ResourceManager.GetString("subject_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. Please activate your email address.
        /// </summary>
        internal static string subject_activate_email {
            get {
                return ResourceManager.GetString("subject_activate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. ${__VirtualRootPath} Portal Backup Created.
        /// </summary>
        internal static string subject_backup_created {
            get {
                return ResourceManager.GetString("subject_backup_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. Email change request.
        /// </summary>
        internal static string subject_change_email {
            get {
                return ResourceManager.GetString("subject_change_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab Password Assistance.
        /// </summary>
        internal static string subject_change_password {
            get {
                return ResourceManager.GetString("subject_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. Mobile Phone change request.
        /// </summary>
        internal static string subject_change_phone {
            get {
                return ResourceManager.GetString("subject_change_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outdated].
        /// </summary>
        internal static string subject_change_pwd {
            get {
                return ResourceManager.GetString("subject_change_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. Change of Portal Owner.
        /// </summary>
        internal static string subject_confirm_owner_change {
            get {
                return ResourceManager.GetString("subject_confirm_owner_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TeamLab Portal!.
        /// </summary>
        internal static string subject_congratulations {
            get {
                return ResourceManager.GetString("subject_congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab. Change of Portal Address.
        /// </summary>
        internal static string subject_dns_change {
            get {
                return ResourceManager.GetString("subject_dns_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User message to administrators.
        /// </summary>
        internal static string subject_for_admin_notify {
            get {
                return ResourceManager.GetString("subject_for_admin_notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to Join TeamLab Portal.
        /// </summary>
        internal static string subject_invite {
            get {
                return ResourceManager.GetString("subject_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to Join ${__VirtualRootPath} Portal.
        /// </summary>
        internal static string subject_join {
            get {
                return ResourceManager.GetString("subject_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation of the ${__VirtualRootPath} Portal.
        /// </summary>
        internal static string subject_portal_deactivate {
            get {
                return ResourceManager.GetString("subject_portal_deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of the ${__VirtualRootPath} Portal.
        /// </summary>
        internal static string subject_portal_delete {
            get {
                return ResourceManager.GetString("subject_portal_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of Your Profile on ${__VirtualRootPath} Portal.
        /// </summary>
        internal static string subject_profile_delete {
            get {
                return ResourceManager.GetString("subject_profile_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile at ${__VirtualRootPath} has been Changed.
        /// </summary>
        internal static string subject_profile_updated {
            get {
                return ResourceManager.GetString("subject_profile_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [outdated].
        /// </summary>
        internal static string subject_pwd_reminder {
            get {
                return ResourceManager.GetString("subject_pwd_reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${__VirtualRootPath} Portal Profile Change Notification.
        /// </summary>
        internal static string subject_self_profile_updated {
            get {
                return ResourceManager.GetString("subject_self_profile_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New on Your Portal for $Date.
        /// </summary>
        internal static string subject_send_whats_new {
            get {
                return ResourceManager.GetString("subject_send_whats_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Added to TeamLab Portal.
        /// </summary>
        internal static string subject_user_has_join {
            get {
                return ResourceManager.GetString("subject_user_has_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your TeamLab Portal!.
        /// </summary>
        internal static string subject_you_added {
            get {
                return ResourceManager.GetString("subject_you_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your TeamLab Portal!.
        /// </summary>
        internal static string subject_you_added_after_invite {
            get {
                return ResourceManager.GetString("subject_you_added_after_invite", resourceCulture);
            }
        }
    }
}
