//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesUCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesUCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Files.Resources.FilesUCResource", typeof(FilesUCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить сопроводительный текст.
        /// </summary>
        public static string AddShareMessage {
            get {
                return ResourceManager.GetString("AddShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт Box.net.
        /// </summary>
        public static string ButtonAddBoxNet {
            get {
                return ResourceManager.GetString("ButtonAddBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт DropBox.
        /// </summary>
        public static string ButtonAddDropBox {
            get {
                return ResourceManager.GetString("ButtonAddDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт Google.
        /// </summary>
        public static string ButtonAddGoogle {
            get {
                return ResourceManager.GetString("ButtonAddGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ресурс.
        /// </summary>
        public static string ButtonAddThirdParty {
            get {
                return ResourceManager.GetString("ButtonAddThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the import.
        /// </summary>
        public static string ButtonCancelImport {
            get {
                return ResourceManager.GetString("ButtonCancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change third party info.
        /// </summary>
        public static string ButtonChangeThirdParty {
            get {
                return ResourceManager.GetString("ButtonChangeThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string ButtonClearFilter {
            get {
                return ResourceManager.GetString("ButtonClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ButtonCopyTo {
            get {
                return ResourceManager.GetString("ButtonCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string ButtonCreateFolder {
            get {
                return ResourceManager.GetString("ButtonCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Drawing.
        /// </summary>
        public static string ButtonCreateImage {
            get {
                return ResourceManager.GetString("ButtonCreateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Presentation.
        /// </summary>
        public static string ButtonCreatePresentation {
            get {
                return ResourceManager.GetString("ButtonCreatePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Spreadsheet.
        /// </summary>
        public static string ButtonCreateSpreadsheet {
            get {
                return ResourceManager.GetString("ButtonCreateSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Document.
        /// </summary>
        public static string ButtonCreateText {
            get {
                return ResourceManager.GetString("ButtonCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete third party.
        /// </summary>
        public static string ButtonDeleteThirdParty {
            get {
                return ResourceManager.GetString("ButtonDeleteThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Trash.
        /// </summary>
        public static string ButtonEmptyTrash {
            get {
                return ResourceManager.GetString("ButtonEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ButtonFilterDocument {
            get {
                return ResourceManager.GetString("ButtonFilterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ButtonFilterFile {
            get {
                return ResourceManager.GetString("ButtonFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string ButtonFilterFolder {
            get {
                return ResourceManager.GetString("ButtonFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ButtonFilterImage {
            get {
                return ResourceManager.GetString("ButtonFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string ButtonFilterPresentation {
            get {
                return ResourceManager.GetString("ButtonFilterPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheets.
        /// </summary>
        public static string ButtonFilterSpreadsheet {
            get {
                return ResourceManager.GetString("ButtonFilterSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Size.
        /// </summary>
        public static string ButtonFullScale {
            get {
                return ResourceManager.GetString("ButtonFullScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to My Documents.
        /// </summary>
        public static string ButtonGotoMy {
            get {
                return ResourceManager.GetString("ButtonGotoMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт из....
        /// </summary>
        public static string ButtonImportFrom {
            get {
                return ResourceManager.GetString("ButtonImportFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        public static string ButtonLearnMore {
            get {
                return ResourceManager.GetString("ButtonLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string ButtonMinimize {
            get {
                return ResourceManager.GetString("ButtonMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the import dialog.
        /// </summary>
        public static string ButtonMinimizeImport {
            get {
                return ResourceManager.GetString("ButtonMinimizeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string ButtonMoveTo {
            get {
                return ResourceManager.GetString("ButtonMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Image.
        /// </summary>
        public static string ButtonNextImg {
            get {
                return ResourceManager.GetString("ButtonNextImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Actions.
        /// </summary>
        public static string ButtonOtherAction {
            get {
                return ResourceManager.GetString("ButtonOtherAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Image.
        /// </summary>
        public static string ButtonPrevImg {
            get {
                return ResourceManager.GetString("ButtonPrevImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ButtonRestore {
            get {
                return ResourceManager.GetString("ButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string ButtonRewrite {
            get {
                return ResourceManager.GetString("ButtonRewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Counterclockwise.
        /// </summary>
        public static string ButtonRotateLeft {
            get {
                return ResourceManager.GetString("ButtonRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Clockwise.
        /// </summary>
        public static string ButtonRotateRight {
            get {
                return ResourceManager.GetString("ButtonRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ButtonSelectAll {
            get {
                return ResourceManager.GetString("ButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ButtonSelectFiles {
            get {
                return ResourceManager.GetString("ButtonSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Settings.
        /// </summary>
        public static string ButtonShareAccess {
            get {
                return ResourceManager.GetString("ButtonShareAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Versions.
        /// </summary>
        public static string ButtonShowVersions {
            get {
                return ResourceManager.GetString("ButtonShowVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По автору.
        /// </summary>
        public static string ButtonSortAuthor {
            get {
                return ResourceManager.GetString("ButtonSortAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате.
        /// </summary>
        public static string ButtonSortModified {
            get {
                return ResourceManager.GetString("ButtonSortModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По имени.
        /// </summary>
        public static string ButtonSortName {
            get {
                return ResourceManager.GetString("ButtonSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По размеру.
        /// </summary>
        public static string ButtonSortSize {
            get {
                return ResourceManager.GetString("ButtonSortSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По типу.
        /// </summary>
        public static string ButtonSortType {
            get {
                return ResourceManager.GetString("ButtonSortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наверх.
        /// </summary>
        public static string ButtonUp {
            get {
                return ResourceManager.GetString("ButtonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ButtonZoomIn {
            get {
                return ResourceManager.GetString("ButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ButtonZoomOut {
            get {
                return ResourceManager.GetString("ButtonZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite confirmation.
        /// </summary>
        public static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This action can not be undone. .
        /// </summary>
        public static string ConfirmRemoveDescription {
            get {
                return ResourceManager.GetString("ConfirmRemoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these elements from list?.
        /// </summary>
        public static string ConfirmUnsubscribe {
            get {
                return ResourceManager.GetString("ConfirmUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать ссылку.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Documents.
        /// </summary>
        public static string CorporateFiles {
            get {
                return ResourceManager.GetString("CorporateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder.
        /// </summary>
        public static string DownloadFolder {
            get {
                return ResourceManager.GetString("DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download document.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Know?.
        /// </summary>
        public static string DoYouKnow {
            get {
                return ResourceManager.GetString("DoYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Common Documents&apos; section shows all the documents shared by portal administrator for common access. Only portal administrator can create folders in this section, but with the access granted the portal users can also upload their files here..
        /// </summary>
        public static string EmptyScreenDescrCorporate {
            get {
                return ResourceManager.GetString("EmptyScreenDescrCorporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag-and-drop the files from your computer here to upload them to your portal even more easily..
        /// </summary>
        public static string EmptyScreenDescrDragDrop {
            get {
                return ResourceManager.GetString("EmptyScreenDescrDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Shared with Me&apos; section is used to show the files which your friends or colleagues gave you access to. In case you haven&apos;t seen the latest changes in the documents they are marked &apos;new&apos;. You can remove the files from the list clicking the appropriate button..
        /// </summary>
        public static string EmptyScreenDescrForme {
            get {
                return ResourceManager.GetString("EmptyScreenDescrForme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documents and image files you {0}create{1} or {2}upload{3} to the portal are kept here in &apos;My Documents&apos; section. You can {4}open{5} and {6}edit{7} them using the TeamLab portal editor, share them with friends or colleagues, organize into folders..
        /// </summary>
        public static string EmptyScreenDescrMy {
            get {
                return ResourceManager.GetString("EmptyScreenDescrMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documents and image files you create or upload for your project are kept in this section. You can open and edit them using the TeamLab portal editor, organize into folders..
        /// </summary>
        public static string EmptyScreenDescrProject {
            get {
                return ResourceManager.GetString("EmptyScreenDescrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Recycle Bin&apos; section is where all the deleted files are moved. You can either restore them in case they are deleted by mistake or delete them permanently. Please note, that when you delete the files from the &apos;Recycle Bin&apos; they cannot be restored any longer..
        /// </summary>
        public static string EmptyScreenDescrTrash {
            get {
                return ResourceManager.GetString("EmptyScreenDescrTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to be displayed for this filter here.
        /// </summary>
        public static string EmptyScreenFilter {
            get {
                return ResourceManager.GetString("EmptyScreenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files matching your filter can be displayed in this section. Please select other filter options or clear filter to view all the files in this section. You can also look for the file you need in other sections..
        /// </summary>
        public static string EmptyScreenFilterDescr {
            get {
                return ResourceManager.GetString("EmptyScreenFilterDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to be displayed in this section.
        /// </summary>
        public static string EmptyScreenHeader {
            get {
                return ResourceManager.GetString("EmptyScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file was not found.
        /// </summary>
        public static string ErrorEmptyUploadFileSelected {
            get {
                return ResourceManager.GetString("ErrorEmptyUploadFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Flash.
        /// </summary>
        public static string FlashUploader {
            get {
                return ResourceManager.GetString("FlashUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash uploader version....
        /// </summary>
        public static string FlashUploaderDescription {
            get {
                return ResourceManager.GetString("FlashUploaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укоротить ссылку.
        /// </summary>
        public static string GetShortenLink {
            get {
                return ResourceManager.GetString("GetShortenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with Html.
        /// </summary>
        public static string HtmlUploader {
            get {
                return ResourceManager.GetString("HtmlUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of file conflict .
        /// </summary>
        public static string IfFileNameConflict {
            get {
                return ResourceManager.GetString("IfFileNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Box.Net.
        /// </summary>
        public static string ImportFromBoxNet {
            get {
                return ResourceManager.GetString("ImportFromBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Docs.
        /// </summary>
        public static string ImportFromGoogle {
            get {
                return ResourceManager.GetString("ImportFromGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Zoho.
        /// </summary>
        public static string ImportFromZoho {
            get {
                return ResourceManager.GetString("ImportFromZoho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import in progress.
        /// </summary>
        public static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import to the folder.
        /// </summary>
        public static string ImportToFolder {
            get {
                return ResourceManager.GetString("ImportToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string MainHeaderSelectAll {
            get {
                return ResourceManager.GetString("MainHeaderSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group management.
        /// </summary>
        public static string ManagmentGroup {
            get {
                return ResourceManager.GetString("ManagmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tree.
        /// </summary>
        public static string OpenTree {
            get {
                return ResourceManager.GetString("OpenTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Possibly this file is a renamed executable file and it cannot be previewed..
        /// </summary>
        public static string PreviewError {
            get {
                return ResourceManager.GetString("PreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you trust this file distributor, download and execute it locally..
        /// </summary>
        public static string PreviewErrorDownload {
            get {
                return ResourceManager.GetString("PreviewErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview documents.
        /// </summary>
        public static string PreviewHeader {
            get {
                return ResourceManager.GetString("PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File conversion in process. This may take some time. Please wait....
        /// </summary>
        public static string PreviewWait {
            get {
                return ResourceManager.GetString("PreviewWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication process....
        /// </summary>
        public static string ProcessAuthentificate {
            get {
                return ResourceManager.GetString("ProcessAuthentificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a web application for internal use designed to store and share files and work on them in team..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project documents.
        /// </summary>
        public static string ProjectFiles {
            get {
                return ResourceManager.GetString("ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        public static string RemoveIsNew {
            get {
                return ResourceManager.GetString("RemoveIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать сопроводительный текст.
        /// </summary>
        public static string RemoveShareMessage {
            get {
                return ResourceManager.GetString("RemoveShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить уведомление.
        /// </summary>
        public static string SendShareNotify {
            get {
                return ResourceManager.GetString("SendShareNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with Me.
        /// </summary>
        public static string SharedForMe {
            get {
                return ResourceManager.GetString("SharedForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет доступ.
        /// </summary>
        public static string SharingLinkCaption {
            get {
                return ResourceManager.GetString("SharingLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab доступ.
        /// </summary>
        public static string SharingListCaption {
            get {
                return ResourceManager.GetString("SharingListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключить на компактный вид.
        /// </summary>
        public static string SwitchViewToCompact {
            get {
                return ResourceManager.GetString("SwitchViewToCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключить на обычный вид.
        /// </summary>
        public static string SwitchViewToNormal {
            get {
                return ResourceManager.GetString("SwitchViewToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received authorization key.
        /// </summary>
        public static string TakeToken {
            get {
                return ResourceManager.GetString("TakeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Third Party.
        /// </summary>
        public static string ThirdPartyDeleteCaption {
            get {
                return ResourceManager.GetString("ThirdPartyDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder title.
        /// </summary>
        public static string ThirdPartyFolderTitle {
            get {
                return ResourceManager.GetString("ThirdPartyFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a shared and put into Shared Documents.
        /// </summary>
        public static string ThirdPartySetCorporate {
            get {
                return ResourceManager.GetString("ThirdPartySetCorporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TitleSelectFile {
            get {
                return ResourceManager.GetString("TitleSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create documents (.docx), spreadsheets (.xlsx), presentations (.pptx) and drawings (.svg) and download them to most popular formats..
        /// </summary>
        public static string TooltipCreate {
            get {
                return ResourceManager.GetString("TooltipCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit the following files: {0}..
        /// </summary>
        public static string TooltipEdit {
            get {
                return ResourceManager.GetString("TooltipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can open the files with the following extentions: {0}..
        /// </summary>
        public static string TooltipOpen {
            get {
                return ResourceManager.GetString("TooltipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload to Documents any files you want..
        /// </summary>
        public static string TooltipUpload {
            get {
                return ResourceManager.GetString("TooltipUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found.
        /// </summary>
        public static string TotalFound {
            get {
                return ResourceManager.GetString("TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from List.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
