//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMJSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMJSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.CRM.Resources.CRMJSResource", typeof(CRMJSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual date of the deal.
        /// </summary>
        public static string ActualCloseDate {
            get {
                return ResourceManager.GetString("ActualCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Checkbox.
        /// </summary>
        public static string AddCheckboxButton {
            get {
                return ResourceManager.GetString("AddCheckboxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an opportunity....
        /// </summary>
        public static string AddNewDealProgress {
            get {
                return ResourceManager.GetString("AddNewDealProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add email.
        /// </summary>
        public static string AddNewEmail {
            get {
                return ResourceManager.GetString("AddNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone.
        /// </summary>
        public static string AddNewPhone {
            get {
                return ResourceManager.GetString("AddNewPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a new task.
        /// </summary>
        public static string AddNewTask {
            get {
                return ResourceManager.GetString("AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Option.
        /// </summary>
        public static string AddOptionButton {
            get {
                return ResourceManager.GetString("AddOptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addresses.
        /// </summary>
        public static string AddressGenitivePlural {
            get {
                return ResourceManager.GetString("AddressGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addresses.
        /// </summary>
        public static string AddressGenitiveSingular {
            get {
                return ResourceManager.GetString("AddressGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string AddressNominative {
            get {
                return ResourceManager.GetString("AddressNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressWatermark {
            get {
                return ResourceManager.GetString("AddressWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this task.
        /// </summary>
        public static string AddThisTask {
            get {
                return ResourceManager.GetString("AddThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per day.
        /// </summary>
        public static string BidType_PerDay {
            get {
                return ResourceManager.GetString("BidType_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per hour.
        /// </summary>
        public static string BidType_PerHour {
            get {
                return ResourceManager.GetString("BidType_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        public static string BidType_PerMonth {
            get {
                return ResourceManager.GetString("BidType_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per week.
        /// </summary>
        public static string BidType_PerWeek {
            get {
                return ResourceManager.GetString("BidType_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per year.
        /// </summary>
        public static string BidType_PerYear {
            get {
                return ResourceManager.GetString("BidType_PerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as primary.
        /// </summary>
        public static string CheckAsPrimary {
            get {
                return ResourceManager.GetString("CheckAsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes.
        /// </summary>
        public static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country....
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityWatermark {
            get {
                return ResourceManager.GetString("CityWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change this key?.
        /// </summary>
        public static string ConfirmChangeKey {
            get {
                return ResourceManager.GetString("ConfirmChangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: all previously created forms will no longer work.
        /// </summary>
        public static string ConfirmChangeKeyNote {
            get {
                return ResourceManager.GetString("ConfirmChangeKeyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this opportunity?.
        /// </summary>
        public static string ConfirmDeleteCase {
            get {
                return ResourceManager.GetString("ConfirmDeleteCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        public static string ConfirmDeleteTask {
            get {
                return ResourceManager.GetString("ConfirmDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вся введеная информация будет потеряна.
        ///Выполнить переход?.
        /// </summary>
        public static string ConfirmGoToCustomFieldPage {
            get {
                return ResourceManager.GetString("ConfirmGoToCustomFieldPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your facebook account identifier..
        /// </summary>
        public static string ContactFacebookDescription {
            get {
                return ResourceManager.GetString("ContactFacebookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your LinkedIn account. For example, teamlabdotcom.
        /// </summary>
        public static string ContactLinkedInDescription {
            get {
                return ResourceManager.GetString("ContactLinkedInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your Twitter account. For example, teamlabdotcom.
        /// </summary>
        public static string ContactTwitterDescription {
            get {
                return ResourceManager.GetString("ContactTwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user.
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete company.
        /// </summary>
        public static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &apos;{0}&apos; company?.
        /// </summary>
        public static string DeleteCompanyConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteCompanyConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: this action cannot be undone.
        /// </summary>
        public static string DeleteConfirmNote {
            get {
                return ResourceManager.GetString("DeleteConfirmNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &apos;{0}&apos; opportunity?.
        /// </summary>
        public static string DeleteDealConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteDealConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting opportunity....
        /// </summary>
        public static string DeleteDealInProgress {
            get {
                return ResourceManager.GetString("DeleteDealInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete participant.
        /// </summary>
        public static string DeleteMember {
            get {
                return ResourceManager.GetString("DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &apos;{0}&apos; person?.
        /// </summary>
        public static string DeletePersonConfirmMessage {
            get {
                return ResourceManager.GetString("DeletePersonConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update email.
        /// </summary>
        public static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        public static string EditingDealProgress {
            get {
                return ResourceManager.GetString("EditingDealProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update phone.
        /// </summary>
        public static string EditPhone {
            get {
                return ResourceManager.GetString("EditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update «{0}» field.
        /// </summary>
        public static string EditSelectedCustomField {
            get {
                return ResourceManager.GetString("EditSelectedCustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update a task.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        public static string ElementsSelectedCount {
            get {
                return ResourceManager.GetString("ElementsSelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every opportunity must have a client.
        /// </summary>
        public static string EmptyDealContact {
            get {
                return ResourceManager.GetString("EmptyDealContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the opportunity budget.
        /// </summary>
        public static string EmptyDealExpectedValue {
            get {
                return ResourceManager.GetString("EmptyDealExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every event must be linked with a contact.
        /// </summary>
        public static string EmptyEventContact {
            get {
                return ResourceManager.GetString("EmptyEventContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every event must have a description.
        /// </summary>
        public static string EmptyEventContent {
            get {
                return ResourceManager.GetString("EmptyEventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields of settings can&apos;t be empty.
        /// </summary>
        public static string EmptyFieldsOfSettings {
            get {
                return ResourceManager.GetString("EmptyFieldsOfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element list cannot be empty.
        /// </summary>
        public static string EmptyItemList {
            get {
                return ResourceManager.GetString("EmptyItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every letter must have a body.
        /// </summary>
        public static string EmptyLetterBodyContent {
            get {
                return ResourceManager.GetString("EmptyLetterBodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty message content.
        /// </summary>
        public static string EmptyMessageContent {
            get {
                return ResourceManager.GetString("EmptyMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every task must have a contact.
        /// </summary>
        public static string EmptyTaskContact {
            get {
                return ResourceManager.GetString("EmptyTaskContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every task must have a due date.
        /// </summary>
        public static string EmptyTaskDeadline {
            get {
                return ResourceManager.GetString("EmptyTaskDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every task must have a responsible one.
        /// </summary>
        public static string EmptyTaskResponsible {
            get {
                return ResourceManager.GetString("EmptyTaskResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every task must have a title.
        /// </summary>
        public static string EmptyTaskTitle {
            get {
                return ResourceManager.GetString("EmptyTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено соответствие полю  &apos;Название мероприятия&apos;.
        /// </summary>
        public static string ErrorCasesNotMappingBasicColumn {
            get {
                return ResourceManager.GetString("ErrorCasesNotMappingBasicColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with such a name already exists.
        /// </summary>
        public static string ErrorCompanyAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorCompanyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company is selected.
        /// </summary>
        public static string ErrorCompanyIsNotSelected {
            get {
                return ResourceManager.GetString("ErrorCompanyIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No person is selected.
        /// </summary>
        public static string ErrorContactIsNotSelected {
            get {
                return ResourceManager.GetString("ErrorContactIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields corresponding to the &apos;First Name&apos;, &apos;Last Name&apos; or &apos;Company Name&apos; could not be found.
        /// </summary>
        public static string ErrorContactNotMappingBasicColumn {
            get {
                return ResourceManager.GetString("ErrorContactNotMappingBasicColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} email recipients maximum.
        /// </summary>
        public static string ErrorEmailRecipientsCount {
            get {
                return ResourceManager.GetString("ErrorEmailRecipientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the case title.
        /// </summary>
        public static string ErrorEmptyCaseTitle {
            get {
                return ResourceManager.GetString("ErrorEmptyCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatory fields must not be duplicated.
        /// </summary>
        public static string ErrorMappingMoreBasicColumn {
            get {
                return ResourceManager.GetString("ErrorMappingMoreBasicColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage_AttachCaseAndDealTogether.
        /// </summary>
        public static string ErrorMessage_NoteAttachedToCaseAndDealTogether {
            get {
                return ResourceManager.GetString("ErrorMessage_NoteAttachedToCaseAndDealTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format is not supported.
        /// </summary>
        public static string ErrorMessage_NotImageSupportFormat {
            get {
                return ResourceManager.GetString("ErrorMessage_NotImageSupportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is not supported.
        /// </summary>
        public static string ErrorMessage_NotSupportedFileFormat {
            get {
                return ResourceManager.GetString("ErrorMessage_NotSupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the image to the server.
        /// </summary>
        public static string ErrorMessage_SaveImageError {
            get {
                return ResourceManager.GetString("ErrorMessage_SaveImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string ErrorNotCorrectEmail {
            get {
                return ResourceManager.GetString("ErrorNotCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are columns without correlation rules..
        /// </summary>
        public static string ErrorNotMappingColumn {
            get {
                return ResourceManager.GetString("ErrorNotMappingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено соответствие полям  &apos;Название возможной сделки&apos;, &apos;Ответственный за возможную сделку&apos;.
        /// </summary>
        public static string ErrorOpportunityNotMappingBasicColumn {
            get {
                return ResourceManager.GetString("ErrorOpportunityNotMappingBasicColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person with such first and last name already exists.
        /// </summary>
        public static string ErrorPersonAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorPersonAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено соответствие полям &apos;Название задачи&apos;, &apos;Ответственный&apos;, &apos;Срок выполнения&apos;.
        /// </summary>
        public static string ErrorTaskNotMappingBasicColumn {
            get {
                return ResourceManager.GetString("ErrorTaskNotMappingBasicColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; type is the last one. It cannot be deleted..
        /// </summary>
        public static string ErrorTheLastContactStage {
            get {
                return ResourceManager.GetString("ErrorTheLastContactStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the only opportunity stage. It cannot be deleted..
        /// </summary>
        public static string ErrorTheLastDealMilestone {
            get {
                return ResourceManager.GetString("ErrorTheLastDealMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; category is the last one. It cannot be deleted..
        /// </summary>
        public static string ErrorTheLastTaskCategory {
            get {
                return ResourceManager.GetString("ErrorTheLastTaskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated deal due date.
        /// </summary>
        public static string ExpectedCloseDate {
            get {
                return ResourceManager.GetString("ExpectedCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string FileGenitivePlural {
            get {
                return ResourceManager.GetString("FileGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string FileGenitiveSingular {
            get {
                return ResourceManager.GetString("FileGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string FileNominative {
            get {
                return ResourceManager.GetString("FileNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find account in Facebook.
        /// </summary>
        public static string FindFacebook {
            get {
                return ResourceManager.GetString("FindFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find account in LinkedIn.
        /// </summary>
        public static string FindLinkedIn {
            get {
                return ResourceManager.GetString("FindLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find account in Twitter.
        /// </summary>
        public static string FindTwitter {
            get {
                return ResourceManager.GetString("FindTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recipient list has been generated. {0} Click the links below to pre-populate your email program with the email addresses..
        /// </summary>
        public static string GenerateLinkInfo {
            get {
                return ResourceManager.GetString("GenerateLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In accordance to the rules of columns correlation we scanned your file and found {0} contacts. The lines where correspondences to the obligatory fields could not be found were ignored. Please make sure you need to import all the contacts and start the contact import afterwards..
        /// </summary>
        public static string ImportFromCSVStepThreeDescription {
            get {
                return ResourceManager.GetString("ImportFromCSVStepThreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingProcessing {
            get {
                return ResourceManager.GetString("LoadingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cases.
        /// </summary>
        public static string ManyCases {
            get {
                return ResourceManager.GetString("ManyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companies.
        /// </summary>
        public static string ManyCompanies {
            get {
                return ResourceManager.GetString("ManyCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ManyContacts {
            get {
                return ResourceManager.GetString("ManyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opportunities.
        /// </summary>
        public static string ManyDeals {
            get {
                return ResourceManager.GetString("ManyDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string ManyEvents {
            get {
                return ResourceManager.GetString("ManyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persons.
        /// </summary>
        public static string ManyPersons {
            get {
                return ResourceManager.GetString("ManyPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string ManyTasks {
            get {
                return ResourceManager.GetString("ManyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        public static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next (to preview).
        /// </summary>
        public static string NextPreview {
            get {
                return ResourceManager.GetString("NextPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cases.
        /// </summary>
        public static string NoCases {
            get {
                return ResourceManager.GetString("NoCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No close date.
        /// </summary>
        public static string NoCloseDate {
            get {
                return ResourceManager.GetString("NoCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no companies.
        /// </summary>
        public static string NoCompanies {
            get {
                return ResourceManager.GetString("NoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no contacts.
        /// </summary>
        public static string NoContacts {
            get {
                return ResourceManager.GetString("NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no opportunities.
        /// </summary>
        public static string NoDeals {
            get {
                return ResourceManager.GetString("NoDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no persons.
        /// </summary>
        public static string NoPersons {
            get {
                return ResourceManager.GetString("NoPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no subject.
        /// </summary>
        public static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tasks.
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        public static string OneCase {
            get {
                return ResourceManager.GetString("OneCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        public static string OneCompany {
            get {
                return ResourceManager.GetString("OneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string OneContact {
            get {
                return ResourceManager.GetString("OneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opportunity.
        /// </summary>
        public static string OneDeal {
            get {
                return ResourceManager.GetString("OneDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string OneEvent {
            get {
                return ResourceManager.GetString("OneEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person.
        /// </summary>
        public static string OnePerson {
            get {
                return ResourceManager.GetString("OnePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string OneTask {
            get {
                return ResourceManager.GetString("OneTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall progress.
        /// </summary>
        public static string OverallProgress {
            get {
                return ResourceManager.GetString("OverallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during {0} days.
        /// </summary>
        public static string PerPeriodDays {
            get {
                return ResourceManager.GetString("PerPeriodDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during {0} hours.
        /// </summary>
        public static string PerPeriodHours {
            get {
                return ResourceManager.GetString("PerPeriodHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during {0} months.
        /// </summary>
        public static string PerPeriodMonths {
            get {
                return ResourceManager.GetString("PerPeriodMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during {0} weeks.
        /// </summary>
        public static string PerPeriodWeeks {
            get {
                return ResourceManager.GetString("PerPeriodWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during {0} years.
        /// </summary>
        public static string PerPeriodYears {
            get {
                return ResourceManager.GetString("PerPeriodYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reload the page.
        /// </summary>
        public static string PleaseRefreshThePage {
            get {
                return ResourceManager.GetString("PleaseRefreshThePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible profiles for {0}.
        /// </summary>
        public static string PossibleSocialMediaAccounts {
            get {
                return ResourceManager.GetString("PossibleSocialMediaAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recipients didn&apos;t have email addresses..
        /// </summary>
        public static string RecipientsWithoutEmail {
            get {
                return ResourceManager.GetString("RecipientsWithoutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save field.
        /// </summary>
        public static string SaveField {
            get {
                return ResourceManager.GetString("SaveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file.
        /// </summary>
        public static string SelectCSVFileButton {
            get {
                return ResourceManager.GetString("SelectCSVFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CSV file: {0}.
        /// </summary>
        public static string SelectedCSVFileLabel {
            get {
                return ResourceManager.GetString("SelectedCSVFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices.
        /// </summary>
        public static string SelectOptions {
            get {
                return ResourceManager.GetString("SelectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been successfully updated.
        /// </summary>
        public static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} more from {1}.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMoreButtonText {
            get {
                return ResourceManager.GetString("ShowMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateWatermark {
            get {
                return ResourceManager.GetString("StateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully closed.
        /// </summary>
        public static string SuccessfullyClosed {
            get {
                return ResourceManager.GetString("SuccessfullyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task «{0}» is closed.
        /// </summary>
        public static string TaskIsOver {
            get {
                return ResourceManager.GetString("TaskIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab.com.
        /// </summary>
        public static string TeamLab {
            get {
                return ResourceManager.GetString("TeamLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by {0}.
        /// </summary>
        public static string TeamlabWatermark {
            get {
                return ResourceManager.GetString("TeamlabWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От старта контейнера {0} дней {1} часов {2} минут.
        /// </summary>
        public static string TemplateFixedDeadline {
            get {
                return ResourceManager.GetString("TemplateFixedDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От предыдущей задачи {0} дней {1} часов {2} минут.
        /// </summary>
        public static string TemplateNotFixedDeadline {
            get {
                return ResourceManager.GetString("TemplateNotFixedDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully closed.
        /// </summary>
        public static string UnsuccessfullyClosed {
            get {
                return ResourceManager.GetString("UnsuccessfullyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file «{0}» is being uploaded....
        /// </summary>
        public static string UploadingProgress {
            get {
                return ResourceManager.GetString("UploadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ZipCodeWatermark {
            get {
                return ResourceManager.GetString("ZipCodeWatermark", resourceCulture);
            }
        }
    }
}
